# Generated by Django 5.2.4 on 2025-07-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dupatta_fabric',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Original Price (Strikethrough)'),
        ),
        migrations.AddField(
            model_name='product',
            name='shirt_fabric',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Code (SKU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_image2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thumbnail Image 2 Path'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_image3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thumbnail Image 3 Path'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_image4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thumbnail Image 4 Path'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_image5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thumbnail Image 5 Path'),
        ),
        migrations.AddField(
            model_name='product',
            name='trouser_fabric',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
